sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t amdev83/docker-react .

script:
  - docker run -e CI=true amdev83/docker-react npm run test